/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AjustesRouteImport } from './routes/ajustes';
import { Route as DiccionarioRouteImport } from './routes/diccionario';
import { Route as HistorialRouteImport } from './routes/historial';
import { Route as PermisosRouteImport } from './routes/permisos';
import { Route as RuntimesRouteImport } from './routes/runtimes';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any);
const DiccionarioRoute = DiccionarioRouteImport.update({
  id: '/diccionario',
  path: '/diccionario',
  getParentRoute: () => rootRouteImport,
} as any);
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any);
const PermisosRoute = PermisosRouteImport.update({
  id: '/permisos',
  path: '/permisos',
  getParentRoute: () => rootRouteImport,
} as any);
const RuntimesRoute = RuntimesRouteImport.update({
  id: '/runtimes',
  path: '/runtimes',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/ajustes': typeof AjustesRoute;
  '/diccionario': typeof DiccionarioRoute;
  '/historial': typeof HistorialRoute;
  '/permisos': typeof PermisosRoute;
  '/runtimes': typeof RuntimesRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/ajustes': typeof AjustesRoute;
  '/diccionario': typeof DiccionarioRoute;
  '/historial': typeof HistorialRoute;
  '/permisos': typeof PermisosRoute;
  '/runtimes': typeof RuntimesRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/ajustes': typeof AjustesRoute;
  '/diccionario': typeof DiccionarioRoute;
  '/historial': typeof HistorialRoute;
  '/permisos': typeof PermisosRoute;
  '/runtimes': typeof RuntimesRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/ajustes'
    | '/diccionario'
    | '/historial'
    | '/permisos'
    | '/runtimes';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/ajustes'
    | '/diccionario'
    | '/historial'
    | '/permisos'
    | '/runtimes';
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/diccionario'
    | '/historial'
    | '/permisos'
    | '/runtimes';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AjustesRoute: typeof AjustesRoute;
  DiccionarioRoute: typeof DiccionarioRoute;
  HistorialRoute: typeof HistorialRoute;
  PermisosRoute: typeof PermisosRoute;
  RuntimesRoute: typeof RuntimesRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/ajustes': {
      id: '/ajustes';
      path: '/ajustes';
      fullPath: '/ajustes';
      preLoaderRoute: typeof AjustesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/diccionario': {
      id: '/diccionario';
      path: '/diccionario';
      fullPath: '/diccionario';
      preLoaderRoute: typeof DiccionarioRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/historial': {
      id: '/historial';
      path: '/historial';
      fullPath: '/historial';
      preLoaderRoute: typeof HistorialRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/permisos': {
      id: '/permisos';
      path: '/permisos';
      fullPath: '/permisos';
      preLoaderRoute: typeof PermisosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/runtimes': {
      id: '/runtimes';
      path: '/runtimes';
      fullPath: '/runtimes';
      preLoaderRoute: typeof RuntimesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  DiccionarioRoute: DiccionarioRoute,
  HistorialRoute: HistorialRoute,
  PermisosRoute: PermisosRoute,
  RuntimesRoute: RuntimesRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
